services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"     # DNS
      - "80:80/tcp"      # HTTP
      - "443:443/tcp"    # HTTPS (Self-signed)
    environment:
      TZ: 'Asia/Taipei'
      FTLCONF_webserver_api_password: 'your_secure_password'
      FTLCONF_dns_listeningMode: 'all' # Required for Docker bridge network
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN # Required for DHCP server
      - SYS_TIME  # Required for NTP client
      - SYS_NICE  # Optional: improves process priority
    restart: unless-stopped