services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"     # DNS
      - "8001:80/tcp"      # HTTP
      # - "443:443/tcp"    # HTTPS
    environment:
      TZ: 'Asia/Taipei'
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN # For DHCP
      - SYS_TIME  # For NTP
      - SYS_NICE  # For process priority
    restart: unless-stopped