services:
  reverse-proxy:
    build: .
    container_name: my-nginx-proxy
    ports:
      - "80:80"
    extra_hosts:
      # Maps your custom strings to your computer's local IP
      - "pihole-server:host-gateway"
      - "wlingo-server:host-gateway"
    # Ensure the container restarts if your computer reboots
    restart: always