services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"    # API Port
      - "9001:9001"    # Web Console Port
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "strongpassword123"
    volumes:
      - ./data:/data
    restart: always
    command: server /data --console-address ":9001"
